using Source.Models;

/// <summary>
/// This class is manual-generated by NozzNazz and based on <see cref="Regions"/>.
/// </summary>
internal static class Areas
{
  public static Area Center { get; set; } = new Area(Regions.Center);
  public static Area EastBarracksBottom { get; set; } = new Area(Regions.EastBarracksBottom);
  public static Area EastBarracksMiddle { get; set; } = new Area(Regions.EastBarracksMiddle);
  public static Area EastBarracksTop { get; set; } = new Area(Regions.EastBarracksTop);
  public static Area EastBase { get; set; } = new Area(Regions.EastBase);
  public static Area EastSpawnBarracksBottom { get; set; } = new Area(Regions.EastSpawnBarracksBottom);
  public static Area EastSpawnBarracksMiddle { get; set; } = new Area(Regions.EastSpawnBarracksMiddle);
  public static Area EastSpawnBarracksTop { get; set; } = new Area(Regions.EastSpawnBarracksTop);
  public static Area EastSpawnBottom { get; set; } = new Area(Regions.EastSpawnBottom);
  public static Area EastSpawnMiddle { get; set; } = new Area(Regions.EastSpawnMiddle);
  public static Area EastSpawnTop { get; set; } = new Area(Regions.EastSpawnTop);
  public static Area HeroSelectorSpawn { get; set; } = new Area(Regions.HeroSelectorSpawn);
  public static Area SouthBarracksLeft { get; set; } = new Area(Regions.SouthBarracksLeft);
  public static Area SouthBarracksMiddle { get; set; } = new Area(Regions.SouthBarracksMiddle);
  public static Area SouthBarracksRight { get; set; } = new Area(Regions.SouthBarracksRight);
  public static Area SouthBase { get; set; } = new Area(Regions.SouthBase);
  public static Area SouthSpawnBarracksLeft { get; set; } = new Area(Regions.SouthSpawnBarracksLeft);
  public static Area SouthSpawnBarracksMiddle { get; set; } = new Area(Regions.SouthSpawnBarracksMiddle);
  public static Area SouthSpawnBarracksRight { get; set; } = new Area(Regions.SouthSpawnBarracksRight);
  public static Area SouthSpawnLeft { get; set; } = new Area(Regions.SouthSpawnLeft);
  public static Area SouthSpawnMiddle { get; set; } = new Area(Regions.SouthSpawnMiddle);
  public static Area SouthSpawnRight { get; set; } = new Area(Regions.SouthSpawnRight);
  public static Area WestBarracksBottom { get; set; } = new Area(Regions.WestBarracksBottom);
  public static Area WestBarracksMiddle { get; set; } = new Area(Regions.WestBarracksMiddle);
  public static Area WestBarracksTop { get; set; } = new Area(Regions.WestBarracksTop);
  public static Area WestBase { get; set; } = new Area(Regions.WestBase);
  public static Area WestSpawnBarracksBottom { get; set; } = new Area(Regions.WestSpawnBarracksBottom);
  public static Area WestSpawnBarracksMiddle { get; set; } = new Area(Regions.WestSpawnBarracksMiddle);
  public static Area WestSpawnBarracksTop { get; set; } = new Area(Regions.WestSpawnBarracksTop);
  public static Area WestSpawnBottom { get; set; } = new Area(Regions.WestSpawnBottom);
  public static Area WestSpawnMiddle { get; set; } = new Area(Regions.WestSpawnMiddle);
  public static Area WestSpawnTop { get; set; } = new Area(Regions.WestSpawnTop);

}