using Source.Models;

/// <summary>
/// This class is manual-generated by NozzNazz and based on <see cref="Regions"/>.
/// </summary>
internal static class Areas
{
  public static Area Center { get; set; } = new Area(Regions.Center);
  public static Area ElfBarracksToCenter { get; set; } = new Area(Regions.ElfBarracksToCenter);
  public static Area ElfBarracksToCenterSpawn { get; set; } = new Area(Regions.ElfBarracksToCenterSpawn);
  public static Area ElfBarracksToHuman { get; set; } = new Area(Regions.ElfBarracksToHuman);
  public static Area ElfBarracksToHumanSpawn { get; set; } = new Area(Regions.ElfBarracksToHumanSpawn);
  public static Area ElfBarracksToUndead { get; set; } = new Area(Regions.ElfBarracksToUndead);
  public static Area ElfBarracksToUndeadSpawn { get; set; } = new Area(Regions.ElfBarracksToUndeadSpawn);
  public static Area ElfBase { get; set; } = new Area(Regions.ElfBase);
  public static Area ElfBaseToCenterSpawn { get; set; } = new Area(Regions.ElfBaseToCenterSpawn);
  public static Area ElfBaseToHumanSpawn { get; set; } = new Area(Regions.ElfBaseToHumanSpawn);
  public static Area ElfBaseToUndeadSpawn { get; set; } = new Area(Regions.ElfBaseToUndeadSpawn);
  public static Area HeroSelectorSpawn { get; set; } = new Area(Regions.HeroSelectorSpawn);
  public static Area HumanBarracksToCenter { get; set; } = new Area(Regions.HumanBarracksToCenter);
  public static Area HumanBarracksToCenterSpawn { get; set; } = new Area(Regions.HumanBarracksToCenterSpawn);
  public static Area HumanBarracksToElf { get; set; } = new Area(Regions.HumanBarracksToElf);
  public static Area HumanBarracksToElfSpawn { get; set; } = new Area(Regions.HumanBarracksToElfSpawn);
  public static Area HumanBarracksToOrcs { get; set; } = new Area(Regions.HumanBarracksToOrcs);
  public static Area HumanBarracksToOrcsSpawn { get; set; } = new Area(Regions.HumanBarracksToOrcsSpawn);
  public static Area HumanBase { get; set; } = new Area(Regions.HumanBase);
  public static Area HumanBaseToCenterSpawn { get; set; } = new Area(Regions.HumanBaseToCenterSpawn);
  public static Area HumanBaseToElfSpawn { get; set; } = new Area(Regions.HumanBaseToElfSpawn);
  public static Area HumanBaseToOrcsSpawn { get; set; } = new Area(Regions.HumanBaseToOrcsSpawn);
  public static Area OrcBarracksToCenter { get; set; } = new Area(Regions.OrcBarracksToCenter);
  public static Area OrcBarracksToCenterSpawn { get; set; } = new Area(Regions.OrcBarracksToCenterSpawn);
  public static Area OrcBarracksToHuman { get; set; } = new Area(Regions.OrcBarracksToHuman);
  public static Area OrcBarracksToHumanSpawn { get; set; } = new Area(Regions.OrcBarracksToHumanSpawn);
  public static Area OrcBarracksToUndead { get; set; } = new Area(Regions.OrcBarracksToUndead);
  public static Area OrcBarracksToUndeadSpawn { get; set; } = new Area(Regions.OrcBarracksToUndeadSpawn);
  public static Area OrcBase { get; set; } = new Area(Regions.OrcBase);
  public static Area OrcBaseToCenterSpawn { get; set; } = new Area(Regions.OrcBaseToCenterSpawn);
  public static Area OrcBaseToHumanSpawn { get; set; } = new Area(Regions.OrcBaseToHumanSpawn);
  public static Area OrcBaseToUndeadSpawn { get; set; } = new Area(Regions.OrcBaseToUndeadSpawn);
  public static Area UndeadBarracksToCenter { get; set; } = new Area(Regions.UndeadBarracksToCenter);
  public static Area UndeadBarracksToCenterSpawn { get; set; } = new Area(Regions.UndeadBarracksToCenterSpawn);
  public static Area UndeadBarracksToElf { get; set; } = new Area(Regions.UndeadBarracksToElf);
  public static Area UndeadBarracksToElfSpawn { get; set; } = new Area(Regions.UndeadBarracksToElfSpawn);
  public static Area UndeadBarracksToOrcs { get; set; } = new Area(Regions.UndeadBarracksToOrcs);
  public static Area UndeadBarracksToOrcsSpawn { get; set; } = new Area(Regions.UndeadBarracksToOrcsSpawn);
  public static Area UndeadBase { get; set; } = new Area(Regions.UndeadBase);
  public static Area UndeadBaseToCenterSpawn { get; set; } = new Area(Regions.UndeadBaseToCenterSpawn);
  public static Area UndeadBaseToElfSpawn { get; set; } = new Area(Regions.UndeadBaseToElfSpawn);
  public static Area UndeadBaseToOrcsSpawn { get; set; } = new Area(Regions.UndeadBaseToOrcsSpawn);

}