namespace Source
{
  /// <summary>
  /// This class is manual-generated by NozzNazz />.
  /// </summary>
  internal static class ConstantsEx
  {
    internal const int WEATHER_Northend_Blizzard = 1397645939;
    internal const int WEATHER_Rays_of_Moonlight = 1280470369;
    internal const int WEATHER_Rays_of_Sunlight = 1280467297;
    internal const int WEATHER_Ashenvale_Heavy_Rain = 1380018290;
    internal const int WEATHER_Northend_Heavy_Snow = 1397647475;
    internal const int WEATHER_Lorderon_Heavy_Rain = 1380739186;
    internal const int WEATHER_Dungeon_Heavy_RedFog = 1178890856;
    internal const int WEATHER_Outland_Heavy_Wind = 1464820599;

    internal const int PlayerId_Humans = 0;
    internal const int PlayerId_Orcs = 4;
    internal const int PlayerId_Elves = 8;
    internal const int PlayerId_Undeads = 12;

    internal const string ColorHexCode_Gold = "ffffcc00";
    internal const string ColorHexCode_Red = "ffff0000";
    internal const string ColorHexCode_Yellow = "ffffff00";
    internal const string ColorHexCode_Gray = "ff808080";
    internal const string ColorHexCode_Maroon = "ff800000"; // Dark red
    internal const string ColorHexCode_DarkGrey = "ff404040";

    internal const int Interval_SpawnTime_Short = 15;
    internal const int Interval_SpawnTime_Middle = 30;
    internal const int Interval_SpawnTime_Long = 60;

    internal const string ForceName_DemonLegion = "Demon Legion";

    internal const string Message_FightToTheDeath = "Fight to the death, you rags!";

#if DEBUG
    internal const float Interval_Event_Klatschen = 60f; //360f;
#else
    internal const float Interval_Event_Klatschen = 900f;
#endif

  }
}