namespace Source
{
  /// <summary>
  /// This class is manual-generated by NozzNazz />.
  /// </summary>
  public static class ConstantsEx
  {
    public const int WEATHER_Northend_Blizzard = 1397645939;
    public const int WEATHER_Rays_of_Moonlight = 1280470369;
    public const int WEATHER_Rays_of_Sunlight = 1280467297;
    public const int WEATHER_Ashenvale_Heavy_Rain = 1380018290;
    public const int WEATHER_Northend_Heavy_Snow = 1397647475;
    public const int WEATHER_Lorderon_Heavy_Rain = 1380739186;
    public const int WEATHER_Dungeon_Heavy_RedFog = 1178890856;
    public const int WEATHER_Outland_Heavy_Wind = 1464820599;
  }
}