using WCSharp.Shared.Data;

/// <summary>
/// This class is auto-generated by WCSharp.ConstantGenerator.
/// </summary>
public static class Regions
{
	public static Rectangle Center { get; set; } = new Rectangle(-128f, 2944f, 128f, 3200f);
	public static Rectangle CenterComplete { get; set; } = new Rectangle(-1024f, 2048f, 1024f, 4096f);
	public static Rectangle ElfBarracksToCenter { get; set; } = new Rectangle(-6208f, -3136f, -6080f, -3008f);
	public static Rectangle ElfBarracksToCenterSpawn { get; set; } = new Rectangle(-6016f, -3584f, -5760f, -2560f);
	public static Rectangle ElfBarracksToHuman { get; set; } = new Rectangle(-10304f, -1984f, -10176f, -1856f);
	public static Rectangle ElfBarracksToHumanSpawn { get; set; } = new Rectangle(-10752f, -1792f, -9728f, -1536f);
	public static Rectangle ElfBarracksToUndead { get; set; } = new Rectangle(-5056f, -7232f, -4928f, -7104f);
	public static Rectangle ElfBarracksToUndeadSpawn { get; set; } = new Rectangle(-4864f, -7680f, -4608f, -6656f);
	public static Rectangle ElfBase { get; set; } = new Rectangle(-10304f, -7232f, -10176f, -7104f);
	public static Rectangle ElfBaseHeroRespawn { get; set; } = new Rectangle(-11136f, -8064f, -11008f, -7936f);
	public static Rectangle ElfBaseHeroSpawn { get; set; } = new Rectangle(-10816f, -7744f, -10688f, -7616f);
	public static Rectangle ElfBaseToCenterSpawn { get; set; } = new Rectangle(-9984f, -6912f, -9728f, -6656f);
	public static Rectangle ElfBaseToHumanSpawn { get; set; } = new Rectangle(-10368f, -6912f, -10112f, -6656f);
	public static Rectangle ElfBaseToUndeadSpawn { get; set; } = new Rectangle(-9984f, -7296f, -9728f, -7040f);
	public static Rectangle ElfToHumanInnerLine { get; set; } = new Rectangle(-10304f, -5184f, -10176f, -5056f);
	public static Rectangle ElfToHumanOuterLine { get; set; } = new Rectangle(-10304f, -1088f, -10176f, -960f);
	public static Rectangle ElfToOrcInnerLine { get; set; } = new Rectangle(-8768f, -5696f, -8640f, -5568f);
	public static Rectangle ElfToOrcOuterLine { get; set; } = new Rectangle(-5184f, -2112f, -5056f, -1984f);
	public static Rectangle ElfToUndeadInnerLine { get; set; } = new Rectangle(-8256f, -7232f, -8128f, -7104f);
	public static Rectangle ElfToUndeadOuterLine { get; set; } = new Rectangle(-4160f, -7232f, -4032f, -7104f);
	public static Rectangle HeroSelectorSpawn { get; set; } = new Rectangle(-18496f, 18112f, -18368f, 18240f);
	public static Rectangle HumanBarracksToCenter { get; set; } = new Rectangle(-6208f, 9152f, -6080f, 9280f);
	public static Rectangle HumanBarracksToCenterSpawn { get; set; } = new Rectangle(-6016f, 8704f, -5760f, 9728f);
	public static Rectangle HumanBarracksToElf { get; set; } = new Rectangle(-10304f, 8000f, -10176f, 8128f);
	public static Rectangle HumanBarracksToElfSpawn { get; set; } = new Rectangle(-10752f, 7680f, -9728f, 7936f);
	public static Rectangle HumanBarracksToOrc { get; set; } = new Rectangle(-5056f, 13248f, -4928f, 13376f);
	public static Rectangle HumanBarracksToOrcSpawn { get; set; } = new Rectangle(-4864f, 12800f, -4608f, 13824f);
	public static Rectangle HumanBase { get; set; } = new Rectangle(-10304f, 13248f, -10176f, 13376f);
	public static Rectangle HumanBaseHeroRespawn { get; set; } = new Rectangle(-11136f, 14080f, -11008f, 14208f);
	public static Rectangle HumanBaseHeroSpawn { get; set; } = new Rectangle(-10816f, 13760f, -10688f, 13888f);
	public static Rectangle HumanBaseToCenterSpawn { get; set; } = new Rectangle(-9984f, 12800f, -9728f, 13056f);
	public static Rectangle HumanBaseToElfSpawn { get; set; } = new Rectangle(-10368f, 12800f, -10112f, 13056f);
	public static Rectangle HumanBaseToOrcSpawn { get; set; } = new Rectangle(-9984f, 13184f, -9728f, 13440f);
	public static Rectangle HumanToElfInnerLine { get; set; } = new Rectangle(-10304f, 11200f, -10176f, 11328f);
	public static Rectangle HumanToElfOuterLine { get; set; } = new Rectangle(-10304f, 7104f, -10176f, 7232f);
	public static Rectangle HumanToOrcInnerLine { get; set; } = new Rectangle(-8256f, 13248f, -8128f, 13376f);
	public static Rectangle HumanToOrcOuterLine { get; set; } = new Rectangle(-4160f, 13248f, -4032f, 13376f);
	public static Rectangle HumanToUndeadInnerLine { get; set; } = new Rectangle(-8768f, 11712f, -8640f, 11840f);
	public static Rectangle HumanToUndeadOuterLine { get; set; } = new Rectangle(-5184f, 8128f, -5056f, 8256f);
	public static Rectangle OrcBarracksToCenter { get; set; } = new Rectangle(6080f, 9152f, 6208f, 9280f);
	public static Rectangle OrcBarracksToCenterSpawn { get; set; } = new Rectangle(5760f, 8704f, 6016f, 9728f);
	public static Rectangle OrcBarracksToHuman { get; set; } = new Rectangle(4928f, 13248f, 5056f, 13376f);
	public static Rectangle OrcBarracksToHumanSpawn { get; set; } = new Rectangle(4608f, 12800f, 4864f, 13824f);
	public static Rectangle OrcBarracksToUndead { get; set; } = new Rectangle(10176f, 8000f, 10304f, 8128f);
	public static Rectangle OrcBarracksToUndeadSpawn { get; set; } = new Rectangle(9728f, 7680f, 10752f, 7936f);
	public static Rectangle OrcBase { get; set; } = new Rectangle(10176f, 13248f, 10304f, 13376f);
	public static Rectangle OrcBaseHeroRespawn { get; set; } = new Rectangle(11008f, 14080f, 11136f, 14208f);
	public static Rectangle OrcBaseHeroSpawn { get; set; } = new Rectangle(10688f, 13760f, 10816f, 13888f);
	public static Rectangle OrcBaseToCenterSpawn { get; set; } = new Rectangle(9728f, 12800f, 9984f, 13056f);
	public static Rectangle OrcBaseToHumanSpawn { get; set; } = new Rectangle(9728f, 13184f, 9984f, 13440f);
	public static Rectangle OrcBaseToUndeadSpawn { get; set; } = new Rectangle(10112f, 12800f, 10368f, 13056f);
	public static Rectangle OrcToElfInnerLine { get; set; } = new Rectangle(8640f, 11712f, 8768f, 11840f);
	public static Rectangle OrcToElfOuterLine { get; set; } = new Rectangle(5056f, 8128f, 5184f, 8256f);
	public static Rectangle OrcToHumanInnerLine { get; set; } = new Rectangle(8128f, 13248f, 8256f, 13376f);
	public static Rectangle OrcToHumanOuterLine { get; set; } = new Rectangle(4032f, 13248f, 4160f, 13376f);
	public static Rectangle OrcToUndeadInnerLine { get; set; } = new Rectangle(10176f, 11200f, 10304f, 11328f);
	public static Rectangle OrcToUndeadOuterLine { get; set; } = new Rectangle(10176f, 7104f, 10304f, 7232f);
	public static Rectangle TestArea { get; set; } = new Rectangle(17280f, 17280f, 17408f, 17408f);
	public static Rectangle UndeadBarracksToCenter { get; set; } = new Rectangle(6080f, -3136f, 6208f, -3008f);
	public static Rectangle UndeadBarracksToCenterSpawn { get; set; } = new Rectangle(5760f, -3584f, 6016f, -2560f);
	public static Rectangle UndeadBarracksToElf { get; set; } = new Rectangle(4928f, -7232f, 5056f, -7104f);
	public static Rectangle UndeadBarracksToElfSpawn { get; set; } = new Rectangle(4608f, -7680f, 4864f, -6656f);
	public static Rectangle UndeadBarracksToOrc { get; set; } = new Rectangle(10176f, -1984f, 10304f, -1856f);
	public static Rectangle UndeadBarracksToOrcSpawn { get; set; } = new Rectangle(9728f, -1792f, 10752f, -1536f);
	public static Rectangle UndeadBase { get; set; } = new Rectangle(10176f, -7232f, 10304f, -7104f);
	public static Rectangle UndeadBaseHeroRespawn { get; set; } = new Rectangle(11008f, -8064f, 11136f, -7936f);
	public static Rectangle UndeadBaseHeroSpawn { get; set; } = new Rectangle(10688f, -7744f, 10816f, -7616f);
	public static Rectangle UndeadBaseToCenterSpawn { get; set; } = new Rectangle(9728f, -6912f, 9984f, -6656f);
	public static Rectangle UndeadBaseToElfSpawn { get; set; } = new Rectangle(9728f, -7296f, 9984f, -7040f);
	public static Rectangle UndeadBaseToOrcSpawn { get; set; } = new Rectangle(10112f, -6912f, 10368f, -6656f);
	public static Rectangle UndeadToElfInnerLine { get; set; } = new Rectangle(8128f, -7232f, 8256f, -7104f);
	public static Rectangle UndeadToElfOuterLine { get; set; } = new Rectangle(4032f, -7232f, 4160f, -7104f);
	public static Rectangle UndeadToHumanInnerLine { get; set; } = new Rectangle(8640f, -5696f, 8768f, -5568f);
	public static Rectangle UndeadToHumanOuterLine { get; set; } = new Rectangle(5056f, -2112f, 5184f, -1984f);
	public static Rectangle UndeadToOrcInnerLine { get; set; } = new Rectangle(10176f, -5184f, 10304f, -5056f);
	public static Rectangle UndeadToOrcOuterLine { get; set; } = new Rectangle(10176f, -1088f, 10304f, -960f);

}