using WCSharp.Shared.Data;

/// <summary>
/// This class is auto-generated by WCSharp.ConstantGenerator.
/// </summary>
public static class Regions
{
	public static Rectangle Center { get; set; } = new Rectangle(-128f, -2176f, 128f, -1920f);
	public static Rectangle ElfBarracksToCenter { get; set; } = new Rectangle(-14592f, -16640f, -14464f, -16512f);
	public static Rectangle ElfBarracksToCenterSpawn { get; set; } = new Rectangle(-14400f, -16448f, -14272f, -16320f);
	public static Rectangle ElfBarracksToHuman { get; set; } = new Rectangle(-15424f, -16576f, -15296f, -16448f);
	public static Rectangle ElfBarracksToHumanSpawn { get; set; } = new Rectangle(-15424f, -16320f, -15296f, -16192f);
	public static Rectangle ElfBarracksToUndead { get; set; } = new Rectangle(-14528f, -17472f, -14400f, -17344f);
	public static Rectangle ElfBarracksToUndeadSpawn { get; set; } = new Rectangle(-14272f, -17472f, -14144f, -17344f);
	public static Rectangle ElfBase { get; set; } = new Rectangle(-15424f, -17472f, -15296f, -17344f);
	public static Rectangle ElfBaseToCenterSpawn { get; set; } = new Rectangle(-14976f, -17024f, -14848f, -16896f);
	public static Rectangle ElfBaseToHumanSpawn { get; set; } = new Rectangle(-15424f, -17024f, -15296f, -16896f);
	public static Rectangle ElfBaseToUndeadSpawn { get; set; } = new Rectangle(-14976f, -17472f, -14848f, -17344f);
	public static Rectangle HeroSelectorSpawn { get; set; } = new Rectangle(-18176f, 18048f, -18048f, 18176f);
	public static Rectangle HumanBarracksToCenter { get; set; } = new Rectangle(-14592f, 12416f, -14464f, 12544f);
	public static Rectangle HumanBarracksToCenterSpawn { get; set; } = new Rectangle(-14400f, 12224f, -14272f, 12352f);
	public static Rectangle HumanBarracksToElf { get; set; } = new Rectangle(-15424f, 8064f, -15296f, 8192f);
	public static Rectangle HumanBarracksToElfSpawn { get; set; } = new Rectangle(-15424f, 7808f, -15296f, 7936f);
	public static Rectangle HumanBarracksToOrcs { get; set; } = new Rectangle(-10240f, 13248f, -10112f, 13376f);
	public static Rectangle HumanBarracksToOrcsSpawn { get; set; } = new Rectangle(-9984f, 13248f, -9856f, 13376f);
	public static Rectangle HumanBase { get; set; } = new Rectangle(-15424f, 13248f, -15296f, 13376f);
	public static Rectangle HumanBaseToCenterSpawn { get; set; } = new Rectangle(-14976f, 12800f, -14848f, 12928f);
	public static Rectangle HumanBaseToElfSpawn { get; set; } = new Rectangle(-15424f, 12800f, -15296f, 12928f);
	public static Rectangle HumanBaseToOrcsSpawn { get; set; } = new Rectangle(-14976f, 13248f, -14848f, 13376f);
	public static Rectangle OrcBarracksToCenter { get; set; } = new Rectangle(14464f, 12416f, 14592f, 12544f);
	public static Rectangle OrcBarracksToCenterSpawn { get; set; } = new Rectangle(14272f, 12224f, 14400f, 12352f);
	public static Rectangle OrcBarracksToHuman { get; set; } = new Rectangle(10112f, 13248f, 10240f, 13376f);
	public static Rectangle OrcBarracksToHumanSpawn { get; set; } = new Rectangle(9856f, 13248f, 9984f, 13376f);
	public static Rectangle OrcBarracksToUndead { get; set; } = new Rectangle(15296f, 8064f, 15424f, 8192f);
	public static Rectangle OrcBarracksToUndeadSpawn { get; set; } = new Rectangle(15296f, 7808f, 15424f, 7936f);
	public static Rectangle OrcBase { get; set; } = new Rectangle(15296f, 13248f, 15424f, 13376f);
	public static Rectangle OrcBaseToCenterSpawn { get; set; } = new Rectangle(14848f, 12800f, 14976f, 12928f);
	public static Rectangle OrcBaseToHumanSpawn { get; set; } = new Rectangle(14848f, 13248f, 14976f, 13376f);
	public static Rectangle OrcBaseToUndeadSpawn { get; set; } = new Rectangle(15296f, 12800f, 15424f, 12928f);
	public static Rectangle UndeadBarracksToCenter { get; set; } = new Rectangle(14464f, -16640f, 14592f, -16512f);
	public static Rectangle UndeadBarracksToCenterSpawn { get; set; } = new Rectangle(14272f, -16448f, 14400f, -16320f);
	public static Rectangle UndeadBarracksToElf { get; set; } = new Rectangle(14400f, -17472f, 14528f, -17344f);
	public static Rectangle UndeadBarracksToElfSpawn { get; set; } = new Rectangle(14144f, -17472f, 14272f, -17344f);
	public static Rectangle UndeadBarracksToOrcs { get; set; } = new Rectangle(15296f, -16576f, 15424f, -16448f);
	public static Rectangle UndeadBarracksToOrcsSpawn { get; set; } = new Rectangle(15296f, -16320f, 15424f, -16192f);
	public static Rectangle UndeadBase { get; set; } = new Rectangle(15296f, -17472f, 15424f, -17344f);
	public static Rectangle UndeadBaseToCenterSpawn { get; set; } = new Rectangle(14848f, -17024f, 14976f, -16896f);
	public static Rectangle UndeadBaseToElfSpawn { get; set; } = new Rectangle(14848f, -17472f, 14976f, -17344f);
	public static Rectangle UndeadBaseToOrcsSpawn { get; set; } = new Rectangle(15296f, -17024f, 15424f, -16896f);

}