using WCSharp.Shared.Data;

/// <summary>
/// This class is auto-generated by WCSharp.ConstantGenerator.
/// </summary>
public static class Regions
{
	public static Rectangle Center { get; set; } = new Rectangle(-128f, 2944f, 128f, 3200f);
	public static Rectangle ElfBarracksToCenter { get; set; } = new Rectangle(-6208f, -3136f, -6080f, -3008f);
	public static Rectangle ElfBarracksToCenterSpawn { get; set; } = new Rectangle(-5952f, -3136f, -5824f, -3008f);
	public static Rectangle ElfBarracksToHuman { get; set; } = new Rectangle(-10304f, -1856f, -10176f, -1728f);
	public static Rectangle ElfBarracksToHumanSpawn { get; set; } = new Rectangle(-10304f, -1600f, -10176f, -1472f);
	public static Rectangle ElfBarracksToUndead { get; set; } = new Rectangle(-4928f, -7232f, -4800f, -7104f);
	public static Rectangle ElfBarracksToUndeadSpawn { get; set; } = new Rectangle(-4672f, -7232f, -4544f, -7104f);
	public static Rectangle ElfBase { get; set; } = new Rectangle(-10304f, -7232f, -10176f, -7104f);
	public static Rectangle ElfBaseHeroRespawn { get; set; } = new Rectangle(-11136f, -8064f, -11008f, -7936f);
	public static Rectangle ElfBaseHeroSpawn { get; set; } = new Rectangle(-10816f, -7744f, -10688f, -7616f);
	public static Rectangle ElfBaseToCenterSpawn { get; set; } = new Rectangle(-9984f, -6912f, -9856f, -6784f);
	public static Rectangle ElfBaseToHumanSpawn { get; set; } = new Rectangle(-10304f, -6912f, -10176f, -6784f);
	public static Rectangle ElfBaseToUndeadSpawn { get; set; } = new Rectangle(-9984f, -7232f, -9856f, -7104f);
	public static Rectangle HeroSelectorSpawn { get; set; } = new Rectangle(-18176f, 18048f, -18048f, 18176f);
	public static Rectangle HumanBarracksToCenter { get; set; } = new Rectangle(-6208f, 9152f, -6080f, 9280f);
	public static Rectangle HumanBarracksToCenterSpawn { get; set; } = new Rectangle(-6208f, 8896f, -6080f, 9024f);
	public static Rectangle HumanBarracksToElf { get; set; } = new Rectangle(-10304f, 7872f, -10176f, 8000f);
	public static Rectangle HumanBarracksToElfSpawn { get; set; } = new Rectangle(-10304f, 7616f, -10176f, 7744f);
	public static Rectangle HumanBarracksToOrcs { get; set; } = new Rectangle(-4928f, 13248f, -4800f, 13376f);
	public static Rectangle HumanBarracksToOrcsSpawn { get; set; } = new Rectangle(-4672f, 13248f, -4544f, 13376f);
	public static Rectangle HumanBase { get; set; } = new Rectangle(-10304f, 13248f, -10176f, 13376f);
	public static Rectangle HumanBaseHeroRespawn { get; set; } = new Rectangle(-11136f, 14080f, -11008f, 14208f);
	public static Rectangle HumanBaseHeroSpawn { get; set; } = new Rectangle(-10816f, 13760f, -10688f, 13888f);
	public static Rectangle HumanBaseToCenterSpawn { get; set; } = new Rectangle(-9984f, 12928f, -9856f, 13056f);
	public static Rectangle HumanBaseToElfSpawn { get; set; } = new Rectangle(-10304f, 12928f, -10176f, 13056f);
	public static Rectangle HumanBaseToOrcsSpawn { get; set; } = new Rectangle(-9984f, 13248f, -9856f, 13376f);
	public static Rectangle OrcBarracksToCenter { get; set; } = new Rectangle(6080f, 9152f, 6208f, 9280f);
	public static Rectangle OrcBarracksToCenterSpawn { get; set; } = new Rectangle(5824f, 9152f, 5952f, 9280f);
	public static Rectangle OrcBarracksToHuman { get; set; } = new Rectangle(4800f, 13248f, 4928f, 13376f);
	public static Rectangle OrcBarracksToHumanSpawn { get; set; } = new Rectangle(4544f, 13248f, 4672f, 13376f);
	public static Rectangle OrcBarracksToUndead { get; set; } = new Rectangle(10176f, 7872f, 10304f, 8000f);
	public static Rectangle OrcBarracksToUndeadSpawn { get; set; } = new Rectangle(10176f, 7616f, 10304f, 7744f);
	public static Rectangle OrcBase { get; set; } = new Rectangle(10176f, 13248f, 10304f, 13376f);
	public static Rectangle OrcBaseHeroRespawn { get; set; } = new Rectangle(11008f, 14080f, 11136f, 14208f);
	public static Rectangle OrcBaseHeroSpawn { get; set; } = new Rectangle(10688f, 13760f, 10816f, 13888f);
	public static Rectangle OrcBaseToCenterSpawn { get; set; } = new Rectangle(9856f, 12928f, 9984f, 13056f);
	public static Rectangle OrcBaseToHumanSpawn { get; set; } = new Rectangle(9856f, 13248f, 9984f, 13376f);
	public static Rectangle OrcBaseToUndeadSpawn { get; set; } = new Rectangle(10176f, 12928f, 10304f, 13056f);
	public static Rectangle UndeadBarracksToCenter { get; set; } = new Rectangle(6080f, -3136f, 6208f, -3008f);
	public static Rectangle UndeadBarracksToCenterSpawn { get; set; } = new Rectangle(6080f, -2880f, 6208f, -2752f);
	public static Rectangle UndeadBarracksToElf { get; set; } = new Rectangle(4800f, -7232f, 4928f, -7104f);
	public static Rectangle UndeadBarracksToElfSpawn { get; set; } = new Rectangle(4544f, -7232f, 4672f, -7104f);
	public static Rectangle UndeadBarracksToOrcs { get; set; } = new Rectangle(10176f, -1856f, 10304f, -1728f);
	public static Rectangle UndeadBarracksToOrcsSpawn { get; set; } = new Rectangle(10176f, -1600f, 10304f, -1472f);
	public static Rectangle UndeadBase { get; set; } = new Rectangle(10176f, -7232f, 10304f, -7104f);
	public static Rectangle UndeadBaseHeroRespawn { get; set; } = new Rectangle(11008f, -8064f, 11136f, -7936f);
	public static Rectangle UndeadBaseHeroSpawn { get; set; } = new Rectangle(10688f, -7744f, 10816f, -7616f);
	public static Rectangle UndeadBaseToCenterSpawn { get; set; } = new Rectangle(9856f, -6912f, 9984f, -6784f);
	public static Rectangle UndeadBaseToElfSpawn { get; set; } = new Rectangle(9856f, -7232f, 9984f, -7104f);
	public static Rectangle UndeadBaseToOrcsSpawn { get; set; } = new Rectangle(10176f, -6912f, 10304f, -6784f);

}